export type Article = {
  id: string
  title: string
  country: string
  region: string
  topic: string
  source: string
  date: string
  summary: string
  why_it_matters: string
  student_takeaway: string
  original_url: string
  approved: boolean
  image_color: string
}

export type Brief = {
  id: string
  title: string
  date: string
  excerpt: string
  read_time: number
}

export const REGIONS = ["Asia", "Europe", "Africa", "Americas", "Middle East", "Oceania", "Global / WHO"]
export const TOPICS = ["Youth", "School", "Social Media", "Policy", "Research", "Crisis & Trauma", "Good News", "Mind & Body"]

export const articles: Article[] = [
  {
    id: "art-001",
    title: "South Korea Expands School Counseling as Youth Stress Reaches Record Levels",
    country: "South Korea",
    region: "Asia",
    topic: "School",
    source: "Reuters Health",
    date: "2026-06-10",
    summary: "South Korea has announced a major expansion of its school counseling programs following data showing that nearly 40% of high school students reported high levels of academic-related anxiety.",
    why_it_matters: "South Korea's education pressure is one of the most intense in the world. When a country with this much academic culture invests in mental health support, it signals a real shift in priorities.",
    student_takeaway: "Schools can make a difference — but students also need safe, stigma-free ways to ask for help before things become a crisis.",
    original_url: "#",
    approved: true,
    image_color: "from-blue-900 to-blue-700",
  },
  {
    id: "art-002",
    title: "WHO Report: 1 in 7 Adolescents Globally Lives With a Mental Health Condition",
    country: "Global",
    region: "Global / WHO",
    topic: "Youth",
    source: "World Health Organization",
    date: "2026-06-08",
    summary: "A new WHO report confirms that mental health conditions affect 1 in 7 adolescents worldwide, with depression and anxiety being the most common — and most under-treated.",
    why_it_matters: "This is a global statistic, not a local one. If your school has 700 students, that's 100 people potentially living with an untreated mental health condition right now.",
    student_takeaway: "Mental health is not rare. Awareness and access to support should be the norm, not the exception.",
    original_url: "#",
    approved: true,
    image_color: "from-teal-900 to-teal-700",
  },
  {
    id: "art-003",
    title: "UK Introduces Social Media Age Restrictions Amid Teen Mental Health Concerns",
    country: "United Kingdom",
    region: "Europe",
    topic: "Social Media",
    source: "BBC Health",
    date: "2026-06-05",
    summary: "The UK government has passed new legislation restricting social media access for users under 16, citing links between algorithm-driven content and rising rates of anxiety and depression in teens.",
    why_it_matters: "This is one of the first national laws directly connecting social media platform design to youth mental health outcomes — it could set a global precedent.",
    student_takeaway: "The debate isn't just about screen time. It's about what algorithms are designed to do to your brain when you're still developing.",
    original_url: "#",
    approved: true,
    image_color: "from-purple-900 to-purple-700",
  },
  {
    id: "art-004",
    title: "Australia Launches 'Beyond Blue Youth' — A Mental Health Platform Built By Teens, For Teens",
    country: "Australia",
    region: "Oceania",
    topic: "Good News",
    source: "Beyond Blue",
    date: "2026-06-03",
    summary: "Australia's Beyond Blue organization has launched a youth-led digital platform where teenagers can find peer-written mental health guides, share experiences anonymously, and connect with verified counselors.",
    why_it_matters: "Mental health support designed by young people tends to feel less clinical and more relatable — which matters when stigma is a major barrier to seeking help.",
    student_takeaway: "Peer-led initiatives work because they speak your language. You might have the skills to create something like this in your own community.",
    original_url: "#",
    approved: true,
    image_color: "from-emerald-900 to-emerald-700",
  },
  {
    id: "art-005",
    title: "Sleep Deprivation Among Students Called a 'Silent Public Health Crisis' in New Research",
    country: "United States",
    region: "Americas",
    topic: "Research",
    source: "NIMH",
    date: "2026-06-01",
    summary: "A comprehensive study by the National Institute of Mental Health found that 73% of high school students get less than 8 hours of sleep per night, with direct links to increased anxiety, poor academic performance, and emotional dysregulation.",
    why_it_matters: "Sleep is not a luxury or a sign of laziness. It is a biological necessity that directly affects how the brain processes emotion and stress.",
    student_takeaway: "No study schedule, no caffeine strategy, and no amount of willpower replaces what sleep does for your brain. It is the most underrated mental health tool you already have access to.",
    original_url: "#",
    approved: true,
    image_color: "from-indigo-900 to-indigo-700",
  },
  {
    id: "art-006",
    title: "Ethiopia Trains 5,000 Community Health Workers in Youth Mental Health First Aid",
    country: "Ethiopia",
    region: "Africa",
    topic: "Policy",
    source: "UNICEF",
    date: "2026-05-28",
    summary: "UNICEF and Ethiopia's Ministry of Health have completed a year-long program training 5,000 community health workers in youth mental health first aid, targeting rural areas with little to no access to professional psychiatric care.",
    why_it_matters: "In many parts of the world, there are no trained mental health professionals within reach. Community-level training is often the only realistic path to support.",
    student_takeaway: "Access to mental health care is deeply unequal globally. Understanding this helps us think about what 'support' really means in different contexts.",
    original_url: "#",
    approved: true,
    image_color: "from-orange-900 to-orange-700",
  },
  {
    id: "art-007",
    title: "Gaza Youth Show Alarming PTSD Rates in First Large-Scale Study Since 2023",
    country: "Palestine",
    region: "Middle East",
    topic: "Crisis & Trauma",
    source: "The Lancet",
    date: "2026-05-25",
    summary: "A new study published in The Lancet found that over 80% of young people in Gaza show symptoms consistent with PTSD, with many having experienced multiple traumatic events, severe displacement, and loss of family members.",
    why_it_matters: "War and displacement leave invisible wounds. Understanding trauma helps us build more empathetic and informed perspectives on global mental health policy.",
    student_takeaway: "Some of the world's most urgent mental health needs are happening right now, to people your age. Awareness is the beginning of advocacy.",
    original_url: "#",
    approved: true,
    image_color: "from-red-900 to-red-800",
  },
  {
    id: "art-008",
    title: "Japan's 'Loneliness Minister' Reports Progress After Two Years of Policy Action",
    country: "Japan",
    region: "Asia",
    topic: "Policy",
    source: "The Guardian",
    date: "2026-05-22",
    summary: "Japan — the first country to appoint a dedicated Minister of Loneliness — has released a two-year progress report showing a measurable reduction in reported loneliness among adults and youth, following community-building investments and workplace policy reforms.",
    why_it_matters: "Loneliness is now recognized as a public health issue, not a personal failure. Japan's approach shows that governments can directly address social isolation.",
    student_takeaway: "Feeling lonely doesn't mean something is wrong with you. But it does mean that connection — real, offline, human connection — matters more than we often acknowledge.",
    original_url: "#",
    approved: true,
    image_color: "from-pink-900 to-pink-700",
  },
  {
    id: "art-009",
    title: "India Faces Mental Health Workforce Shortage as Demand Among Youth Surges",
    country: "India",
    region: "Asia",
    topic: "Policy",
    source: "Reuters Health",
    date: "2026-05-18",
    summary: "India has just 0.3 psychiatrists per 100,000 people — among the lowest ratios globally — as demand for youth mental health services rises sharply in the wake of post-pandemic stress and exam season pressure.",
    why_it_matters: "The gap between need and access is enormous. Policy change and investment in training professionals is critical to closing it.",
    student_takeaway: "If you're interested in public health, psychiatry, or community work — these are some of the places in the world that need you most.",
    original_url: "#",
    approved: true,
    image_color: "from-cyan-900 to-cyan-700",
  },
  {
    id: "art-010",
    title: "France Tests 'Emotional Health Curriculum' in 200 Secondary Schools",
    country: "France",
    region: "Europe",
    topic: "School",
    source: "BBC Health",
    date: "2026-05-15",
    summary: "A pilot program in 200 French secondary schools is teaching students how to identify and name their emotions, manage conflict, and build resilience — skills not typically part of the academic curriculum.",
    why_it_matters: "Emotional literacy — the ability to understand and express feelings — is a proven protective factor against anxiety and depression, yet it's rarely taught in schools.",
    student_takeaway: "Learning how to name what you feel is one of the most practical mental health skills you can develop. It doesn't require a therapist — it requires practice.",
    original_url: "#",
    approved: true,
    image_color: "from-violet-900 to-violet-700",
  },
  {
    id: "art-011",
    title: "Kenya's Youth-Led Mental Health Podcast Reaches 2 Million Listeners Across Africa",
    country: "Kenya",
    region: "Africa",
    topic: "Good News",
    source: "UNICEF",
    date: "2026-05-10",
    summary: "Started by a 19-year-old university student in Nairobi, a mental health podcast in Swahili and English has grown to 2 million listeners across 12 African countries, covering topics from stigma to grief to exam stress.",
    why_it_matters: "Language and cultural relevance are huge barriers to mental health access. Content that speaks to people in their own language and lived context can go further than formal systems.",
    student_takeaway: "You don't need professional credentials to make a difference in mental health awareness. You need empathy, consistency, and a platform — even a small one.",
    original_url: "#",
    approved: true,
    image_color: "from-green-900 to-green-700",
  },
  {
    id: "art-012",
    title: "Brazil Reports Highest Youth Suicide Rates in a Decade — and Launches National Response",
    country: "Brazil",
    region: "Americas",
    topic: "Crisis & Trauma",
    source: "The Guardian",
    date: "2026-05-06",
    summary: "Brazil has recorded its highest rate of youth suicide in ten years, prompting a national response that includes school-based training, a 24/7 youth crisis line, and public campaigns to reduce stigma around asking for help.",
    why_it_matters: "Suicide is preventable. Most people who die by suicide show warning signs. Understanding these signs and knowing how to respond can literally save lives.",
    student_takeaway: "If someone you know seems different — withdrawn, hopeless, giving things away — say something. A direct conversation can open a door that silence keeps closed.",
    original_url: "#",
    approved: true,
    image_color: "from-rose-900 to-rose-700",
  },

  // Taiwan-specific articles
  {
    id: "art-013",
    title: "1 in 5 Taiwanese Teens Reports Suicidal Thoughts, Survey Finds",
    country: "Taiwan",
    region: "Asia",
    topic: "Youth",
    source: "Focus Taiwan / Child Welfare League Foundation",
    date: "2025-09-17",
    summary: "A major survey by Taiwan's Child Welfare League Foundation found that more than 22% of Taiwanese teenagers reported having had suicidal thoughts, with girls reporting stronger feelings than boys. Academic pressure and social media were identified as leading contributing factors.",
    why_it_matters: "Taiwan's academic culture is one of the most intense in Asia. This data shows that the mental health cost of that pressure is real, measurable, and affecting students your age right now.",
    student_takeaway: "These numbers are not abstract — they are your classmates. Knowing the scale of the problem is the first step toward creating a school environment where talking about it is normal.",
    original_url: "https://focustaiwan.tw/society/202509170024",
    approved: true,
    image_color: "from-blue-800 to-blue-600",
  },
  {
    id: "art-014",
    title: "New Taipei Plans to Double Mental Health Centers by 2030 Amid Rising Depression",
    country: "Taiwan",
    region: "Asia",
    topic: "Policy",
    source: "Taiwan News",
    date: "2025-12-17",
    summary: "New Taipei City announced plans to expand its community mental health network from 7 to 14 centers by 2030, in direct response to rising rates of depression and anxiety among youth and adults. The announcement follows data showing psychiatric diagnoses among 15–30 year olds rose nearly 30% between 2016 and 2021.",
    why_it_matters: "Infrastructure investment in mental health is one of the most direct ways governments reduce suffering. More centers means shorter wait times, more accessible support, and fewer crises going unaddressed.",
    student_takeaway: "Government action matters — but it takes time. Understanding the gap between current access and future plans helps you advocate for better support right now.",
    original_url: "https://taiwannews.com.tw/news/6266690",
    approved: true,
    image_color: "from-teal-800 to-teal-600",
  },
  {
    id: "art-015",
    title: "Taiwan Launches Whole-of-Society Mental Health Resilience Program 2025–2030",
    country: "Taiwan",
    region: "Asia",
    topic: "Policy",
    source: "Taiwan Ministry of Health and Welfare",
    date: "2025-10-15",
    summary: "Taiwan's government has launched a six-year national mental health strategy called the Whole-of-Society Mental Health Resilience Program, targeting prevention, access to care, crisis management, and youth support across schools, communities, and workplaces through 2030.",
    why_it_matters: "A national 6-year plan signals that mental health is now a genuine policy priority — not just a health issue but a social and economic one. How this plan is implemented will affect millions of young people.",
    student_takeaway: "Policy documents are not just bureaucracy — they are commitments. Knowing what your government has promised makes it possible to hold them accountable.",
    original_url: "https://nite.taipei/News_Content.aspx?n=B57558CD39F9D3C8&sms=1BBA80E71222F5DB&s=6B9B57EFB879DF06",
    approved: true,
    image_color: "from-green-800 to-green-600",
  },
  {
    id: "art-016",
    title: "Taiwan Students Spend 35 Hours Per Week on Social Media — And Mental Health Is Paying the Price",
    country: "Taiwan",
    region: "Asia",
    topic: "Social Media",
    source: "Child Welfare League Foundation",
    date: "2025-08-20",
    summary: "A survey by Taiwan's Child Welfare League Foundation found that junior and senior high school students spend an average of 35 hours per week on social media — over five hours per day. Students who overuse social media were found to be significantly more prone to anxiety, depression, and sleep disruption.",
    why_it_matters: "Five hours a day is not casual browsing — it is a major part of how Taiwan's teenagers experience the world. The mental health effects of that exposure are increasingly well-documented.",
    student_takeaway: "This isn't about blaming social media. It's about understanding how your attention is being used — and whether that use is working for you or against you.",
    original_url: "https://www.children.org.tw/english/news_detail/2023-Junior-High-Student-Mental-Health",
    approved: true,
    image_color: "from-purple-800 to-purple-600",
  },
  {
    id: "art-017",
    title: "Loneliness Declared a Cross-Generational Crisis in Taiwan — Mental Health Foundation Urges Action",
    country: "Taiwan",
    region: "Asia",
    topic: "Youth",
    source: "Taipei Times",
    date: "2026-02-01",
    summary: "Taiwan's Mental Health Foundation released findings in early 2026 identifying loneliness as a growing, cross-generational problem affecting teenagers, young adults, and the elderly alike. The foundation called for more proactive government policies to address social isolation before it escalates into clinical mental health conditions.",
    why_it_matters: "Loneliness is not just a feeling — it is a health risk. Chronic isolation increases rates of depression, anxiety, and physical illness. Recognizing it as a public health issue is the first step toward addressing it systematically.",
    student_takeaway: "Loneliness looks different from what we expect. It can happen in crowded schools, active group chats, and busy families. Checking in — really checking in — on the people around you matters more than you might think.",
    original_url: "https://www.taipeitimes.com/News/taiwan/archives/2026/02/01/2003851582",
    approved: true,
    image_color: "from-indigo-800 to-indigo-600",
  },

  // Recent international articles
  {
    id: "art-018",
    title: "1 in 5 Teenagers Now Turns to AI Chatbots for Mental Health Support — Without Telling Anyone",
    country: "United States",
    region: "Americas",
    topic: "Social Media",
    source: "Washington Times / RAND Study",
    date: "2026-06-11",
    summary: "A new RAND study found that nearly 1 in 5 American teens and young adults now use AI chatbots for emotional support and mental health advice — and most do so privately, without telling parents, counselors, or clinicians. 64% of US teens use AI chatbots, with 30% doing so daily.",
    why_it_matters: "AI chatbots are becoming an unofficial mental health system for young people — without the safety nets, training, or oversight that clinical care provides. This raises urgent questions about what 'support' really means in the AI era.",
    student_takeaway: "AI can be a starting point for reflection, but it is not therapy, and it cannot replace a real human who knows you. If you use AI for emotional support, also have at least one person in your life you talk to honestly.",
    original_url: "https://www.washingtontimes.com/news/2026/jun/11/nearly-1-5-teens-young-adults-turn-ai-chatbots-mental-health-advice/",
    approved: true,
    image_color: "from-cyan-900 to-cyan-700",
  },
  {
    id: "art-019",
    title: "UN World Youth Report: Mental Health Now Shaped by Six Social Determinants",
    country: "Global",
    region: "Global / WHO",
    topic: "Policy",
    source: "UN DESA",
    date: "2026-02-01",
    summary: "The United Nations released its 2026 World Youth Report on Mental Health and Well-being, concluding that youth mental health is fundamentally shaped by six social determinants: education access, employment, family dynamics, poverty, technology, and societal attitudes — not individual weakness.",
    why_it_matters: "This shifts how we should think about mental health entirely. If your mental health is affected by poverty, unfair school systems, or harmful technology design, the solution is not just individual therapy — it's systemic change.",
    student_takeaway: "Understanding the social determinants of mental health helps you think about it as a justice issue, not just a personal one. Young people who understand this tend to advocate more effectively for change.",
    original_url: "https://social.desa.un.org/issues/youth/news/world-youth-report-highlights-urgent-need-for-inclusive-youth-informed-mental",
    approved: true,
    image_color: "from-emerald-900 to-emerald-700",
  },
  {
    id: "art-020",
    title: "OECD Report: Youth Mental Health Crisis Demands Systemic Response Across 38 Countries",
    country: "Global",
    region: "Global / WHO",
    topic: "Research",
    source: "OECD",
    date: "2026-03-10",
    summary: "A comprehensive OECD report on child, adolescent, and youth mental health across 38 member countries found rising rates of depression, anxiety, and self-harm — with digital technology and academic pressure cited as key new drivers alongside longstanding factors like poverty and family stress.",
    why_it_matters: "When the same mental health trends appear across 38 different countries with very different cultures, economies, and school systems, it tells you something important: this is not a local problem with local solutions.",
    student_takeaway: "Reading about mental health globally helps you see your own experience in a larger context. It also shows you that young people everywhere are dealing with versions of the same challenges — and finding different ways to respond.",
    original_url: "https://www.oecd.org/en/publications/child-adolescent-and-youth-mental-health-in-the-21st-century_1092c3cb-en.html",
    approved: true,
    image_color: "from-violet-900 to-violet-700",
  },
  {
    id: "art-021",
    title: "48% of US Teens Say Social Media Has a Mostly Negative Effect on People Their Age",
    country: "United States",
    region: "Americas",
    topic: "Social Media",
    source: "Axis Intelligence / Pew Research",
    date: "2026-04-15",
    summary: "New data shows that 48% of US teenagers now believe social media has a mostly negative effect on people their age — up 16 percentage points since 2022. TikTok leads average daily time-on-platform at 1 hour 18 minutes per day. Teens are increasingly aware of the harm, yet usage continues to rise.",
    why_it_matters: "The gap between knowing something is harmful and being able to stop is one of the defining mental health challenges of this generation. Understanding that gap is the beginning of navigating it.",
    student_takeaway: "The fact that teenagers themselves are increasingly skeptical of social media is actually a significant shift. Awareness is not the same as control, but it changes the relationship with these platforms.",
    original_url: "https://axis-intelligence.com/teen-social-media-statistics/",
    approved: true,
    image_color: "from-pink-900 to-pink-700",
  },
  {
    id: "art-022",
    title: "Bullied Youth 3.6x More Likely to Rely on AI for Emotional Support, Study Warns",
    country: "United States",
    region: "Americas",
    topic: "Youth",
    source: "Surgo Health / AJMC",
    date: "2026-05-20",
    summary: "Research from Surgo Health found that the young people most likely to turn to AI chatbots for emotional support are also the most vulnerable: those who have been bullied, who feel put down by parents, or who have experienced violence at home are 3.6 times more likely to rely on AI for emotional connection.",
    why_it_matters: "The students who most need safe, supervised human support are turning instead to AI — because it is always available, never judges, and never tells anyone. This is a serious gap in the mental health safety net.",
    student_takeaway: "If you know someone who seems isolated and is spending a lot of time online, that may be worth a real conversation. The people most at risk often don't ask for help — they find workarounds instead.",
    original_url: "https://www.ajmc.com/view/ai-chatbot-use-for-mental-health-advice-rises-sharply-among-us-youth-with-key-disparities-identified",
    approved: true,
    image_color: "from-orange-900 to-orange-700",
  },
]

export const briefs: Brief[] = [
  {
    id: "brief-001",
    title: "What I Learned From Reading Global Mental Health News This Week",
    date: "2026-06-15",
    excerpt: "Every week I read through mental health headlines from around the world. This week, the common thread wasn't the scale of the problem — it was how differently each country is choosing to respond to it.",
    read_time: 4,
  },
  {
    id: "brief-002",
    title: "Why Schools Should Talk About Burnout Before Exam Season, Not During It",
    date: "2026-06-10",
    excerpt: "By the time students are visibly struggling in exam week, the intervention is already late. Burnout builds quietly over months. The conversation needs to start at the beginning of the school year.",
    read_time: 5,
  },
  {
    id: "brief-003",
    title: "Mental Health Is Not Just a Personal Issue — And the Data Proves It",
    date: "2026-06-05",
    excerpt: "We tend to talk about mental health as something that happens to individuals. But policy decisions, school systems, social media design, and economic inequality all shape it. That changes how we should respond.",
    read_time: 6,
  },
  {
    id: "brief-004",
    title: "Sleep Became a Global Student Problem. Here's Why We Keep Ignoring It.",
    date: "2026-06-01",
    excerpt: "The research is not new. Sleep deprivation hurts academic performance, emotional regulation, and long-term health. So why do schools still start before 8am and why do students still badge their all-nighters like achievements?",
    read_time: 5,
  },
  {
    id: "brief-005",
    title: "Why Asking For Help Is Still Hard — Even When You Know It's OK",
    date: "2026-05-25",
    excerpt: "Knowing that mental health is real, that help exists, and that asking for support is not weakness — and still not asking — is a feeling a lot of students know. I've been thinking about why the gap between knowledge and action exists.",
    read_time: 4,
  },
  {
    id: "brief-006",
    title: "What Students Can Actually Learn From Global Mental Health Policies",
    date: "2026-05-18",
    excerpt: "Japan has a Loneliness Minister. France teaches emotional literacy in school. Australia built a mental health platform by and for teenagers. These aren't just policy decisions — they're arguments for what is possible.",
    read_time: 5,
  },
]

export const topics = [
  {
    id: "youth",
    title: "Youth Mental Health",
    icon: "🧠",
    description: "How mental health affects young people globally, from early childhood through adolescence.",
    takeaway: "Youth mental health is not a niche concern — it is a global public health priority.",
    count: 3,
  },
  {
    id: "school",
    title: "School Pressure",
    icon: "📚",
    description: "Academic stress, exam culture, school counseling access, and the mental health cost of high-pressure education systems.",
    takeaway: "Schools can be sources of support — but they can also be sources of significant stress. The design matters.",
    count: 4,
  },
  {
    id: "sleep",
    title: "Sleep & Burnout",
    icon: "🌙",
    description: "Why sleep is a mental health issue, what burnout really looks like, and what research says about recovery.",
    takeaway: "Sleep is not optional. Burnout is not a badge of honor. Both deserve to be taken seriously.",
    count: 2,
  },
  {
    id: "social-media",
    title: "Social Media",
    icon: "📱",
    description: "Algorithm design, social comparison, screen time, and the growing body of research on social media and teen wellbeing.",
    takeaway: "The question isn't just 'how much time' you spend online — it's what the platform is designed to make you feel.",
    count: 3,
  },
  {
    id: "anxiety",
    title: "Anxiety & Depression",
    icon: "🌊",
    description: "Understanding anxiety and depression as clinical realities, not personality traits — globally, not just locally.",
    takeaway: "These are conditions, not character flaws. They affect millions of people, including people who look like they have it all together.",
    count: 4,
  },
  {
    id: "stigma",
    title: "Stigma",
    icon: "🔓",
    description: "Why stigma prevents people from seeking help, how it varies by culture, and what reduces it.",
    takeaway: "Stigma is not individual — it is cultural and structural. It can be changed through conversation, visibility, and education.",
    count: 2,
  },
  {
    id: "suicide",
    title: "Suicide Prevention",
    icon: "🤝",
    description: "Warning signs, how to respond, and the global state of prevention efforts — handled with care and accuracy.",
    takeaway: "Suicide is preventable. Knowing the signs and responding with care — not avoidance — can make a real difference.",
    count: 2,
  },
  {
    id: "crisis",
    title: "War, Crisis & Trauma",
    icon: "🌍",
    description: "How conflict, displacement, disasters, and mass trauma affect youth mental health across the world.",
    takeaway: "Trauma is a global mental health reality. Understanding it builds empathy and supports more effective responses.",
    count: 2,
  },
  {
    id: "policy",
    title: "Mental Health Policy",
    icon: "📋",
    description: "Government action, legislation, healthcare access, and what makes mental health policy work — or fail.",
    takeaway: "Policy is not abstract. It decides who gets support, how fast, and whether it's free.",
    count: 4,
  },
  {
    id: "mind-body",
    title: "Mind & Body Health",
    icon: "💚",
    description: "The connection between mental and physical health — sleep, exercise, nutrition, chronic illness, and more.",
    takeaway: "Mental health and physical health are not separate. Treating one often means addressing the other.",
    count: 3,
  },
]
